export type CommandCategory = 'safety' | 'calibration' | 'ffb' | 'system' | 'diagnostics';

export interface BoardCommand {
  id: string;
  label: string;
  command: string;
  category: CommandCategory;
  description: string;
  expectReply?: boolean;
  timeoutMs?: number;
  danger?: boolean;
}

export const boardCommands: BoardCommand[] = [
  {
    id: 'clear-errors',
    label: 'Clear errors',
    command: 'sc',
    category: 'safety',
    description: 'Clear ODrive latched errors before setup, calibration, or closed loop.',
  },
  {
    id: 'idle',
    label: 'Idle',
    command: 'w axis0.requested_state 1',
    category: 'safety',
    description: 'Disarm axis0 immediately.',
    danger: true,
  },
  {
    id: 'closed-loop',
    label: 'Closed loop',
    command: 'w axis0.requested_state 8',
    category: 'safety',
    description: 'Arm axis0 in CLOSED_LOOP_CONTROL.',
  },
  {
    id: 'motor-calibration',
    label: 'Motor calibration',
    command: 'w axis0.requested_state 4',
    category: 'calibration',
    description: 'Measure motor phase resistance and inductance.',
    timeoutMs: 30000,
  },
  {
    id: 'encoder-offset-calibration',
    label: 'Encoder offset calibration',
    command: 'w axis0.requested_state 7',
    category: 'calibration',
    description: 'Align encoder phase offset. Center the wheel mechanically first.',
    timeoutMs: 60000,
  },
  {
    id: 'full-calibration',
    label: 'Full calibration sequence',
    command: 'w axis0.requested_state 3',
    category: 'calibration',
    description: 'Motor + encoder calibration in one sequence. Wheel must be disconnected.',
    timeoutMs: 90000,
    danger: true,
  },
  {
    id: 'encoder-index-search',
    label: 'Encoder index search',
    command: 'w axis0.requested_state 6',
    category: 'calibration',
    description: 'Search for encoder Z index pulse.',
    timeoutMs: 60000,
  },
  {
    id: 'encoder-dir-find',
    label: 'Encoder direction find',
    command: 'w axis0.requested_state 10',
    category: 'calibration',
    description: 'Detect encoder count direction automatically.',
    timeoutMs: 30000,
  },
  {
    id: 'lockin-spin',
    label: 'Lockin spin',
    command: 'w axis0.requested_state 9',
    category: 'calibration',
    description: 'Open-loop lockin spin for sensorless or encoder alignment.',
    timeoutMs: 30000,
  },
  {
    id: 'homing',
    label: 'Homing',
    command: 'w axis0.requested_state 11',
    category: 'calibration',
    description: 'Axis homing sequence (requires endstop configuration).',
    timeoutMs: 30000,
  },
  {
    id: 'zero-wheel',
    label: 'Zero wheel',
    command: 'axis.zeroenc!',
    category: 'ffb',
    description: 'Capture current position as the logical FFB center.',
  },
  {
    id: 'anticogging-calibration',
    label: 'Anticogging calibration',
    command: 'axis.anticogcal!',
    category: 'ffb',
    description: 'Start ODrive anticogging calibration (ASCII alias Y). Map persists with ss, not sys.save!.',
    timeoutMs: 3000,
  },
  {
    id: 'save-ffb',
    label: 'Save FFB EEPROM',
    command: 'sys.save!',
    category: 'system',
    description: 'Persist FFB/GPIO/axis/filters/zeroofs to emulated EEPROM flash S1+S2. No reboot.',
    timeoutMs: 5000,
  },
  {
    id: 'save-odrive',
    label: 'Save ODrive NVM',
    command: 'ss',
    category: 'system',
    description: 'Persist motor/encoder/controller/boot flags to ODrive NVM (flash S10+S11) and reboot. Not FFB EEPROM.',
    timeoutMs: 8000,
  },
  {
    id: 'reboot',
    label: 'Reboot firmware',
    command: 'sr',
    category: 'system',
    description: 'Soft reset the board into the application firmware.',
    expectReply: false,
  },
  {
    id: 'reboot-dfu',
    label: 'Reboot to DFU',
    command: 'sd',
    category: 'system',
    description: 'Jump to the STM32 ROM bootloader for browser DFU flashing.',
    expectReply: false,
  },
  {
    id: 'ffb-diag',
    label: 'FFB diagnostic summary',
    command: 'd',
    category: 'diagnostics',
    description: 'Read compact FFB counters from the patched ASCII protocol.',
  },
  {
    id: 'ffb-diag-detail',
    label: 'FFB diagnostic detail',
    command: 'D',
    category: 'diagnostics',
    description: 'Read detailed FFB diagnostic state.',
  },
  {
    id: 'torque-diag',
    label: 'Torque diagnostic',
    command: 'T',
    category: 'diagnostics',
    description: 'Read current FFB torque and related counters.',
  },
  {
    id: 'eeprom-dump',
    label: 'FFB EEPROM dump',
    command: 'sys.eedump?',
    category: 'diagnostics',
    description: 'Inspect emulated EEPROM page state and last read/write result.',
  },
  {
    id: 'save-stat',
    label: 'Last save status',
    command: 'sys.savestat?',
    category: 'diagnostics',
    description: 'Read write/error counters from the last sys.save! attempt.',
  },
  {
    id: 'enc-raw',
    label: 'SPI encoder counters',
    command: 'sys.encraw!',
    category: 'diagnostics',
    description: 'Snapshot SPI encoder counters: valid reads, parity/CRC8 errors, and last raw position.',
  },
  {
    id: 'magnet-diag',
    label: 'AS5047 magnet status',
    command: 'sys.magnet!',
    category: 'diagnostics',
    description: 'Read AS5047 DIAAGC register — AGC, field strength flags, magnet health.',
  },
  {
    id: 'mt-status',
    label: 'MT6835 status & warnings',
    command: 'sys.mtstatus?',
    category: 'diagnostics',
    description: 'Read MT6835 magnetic sensor status: boot CRC, hyst0, overspeed, weak field, undervolt, and autocal.',
  },
  {
    id: 'mt-zero',
    label: 'MT6835 set zero',
    command: 'sys.mtzero!',
    category: 'calibration',
    description: 'Set current position as zero on MT6835 (volatile until sys.mteeprom!). Refuses if motor is armed.',
  },
  {
    id: 'mt-eeprom',
    label: 'MT6835 burn EEPROM',
    command: 'sys.mteeprom!',
    category: 'system',
    description: 'Persist MT6835 register map to on-chip EEPROM. Pauses sensor reads for 6.5s. Do NOT power off for 6s!',
    timeoutMs: 10000,
    danger: true,
  },
  {
    id: 'ping',
    label: 'Ping FFB parser',
    command: 'sys.ping?',
    category: 'diagnostics',
    description: 'OpenFFBoard ping — replies pong. Confirms the FFB command parser, not ODrive ASCII.',
  },
  {
    id: 'temp-mosfet',
    label: 'MOSFET temperature',
    command: 'sys.temp?',
    category: 'diagnostics',
    description: 'Read real onboard MOSFET / gate driver temperature in °C.',
  },
  {
    id: 'temp-motor',
    label: 'Motor temperature',
    command: 'sys.motortemp?',
    category: 'diagnostics',
    description: 'Read external motor thermistor temperature in °C.',
  },
  {
    id: 'fxtest',
    label: 'FFB one-line summary',
    command: 'sys.fxtest?',
    category: 'diagnostics',
    description: 'Compact FFB status line from the slim OpenFFBoard layer.',
  },
  {
    id: 'eeprom-test',
    label: 'EEPROM round-trip test',
    command: 'sys.eetest!',
    category: 'diagnostics',
    description: 'Write/read test of FFB emulated EEPROM. Safe diagnostic — does not format.',
    timeoutMs: 5000,
  },
  {
    id: 'eeprom-format',
    label: 'Format FFB EEPROM',
    command: 'sys.eeformat!',
    category: 'system',
    description: 'Force-format FFB EEPROM (S1+S2). Does not erase ODrive NVM. Use se to wipe both.',
    timeoutMs: 8000,
    danger: true,
  },
  {
    id: 'bus-peaks',
    label: 'Bus current/voltage peaks',
    command: 'I',
    category: 'diagnostics',
    description: 'ASCII I — Ibus/motor/VBUS peak min..max since last R reset.',
  },
  {
    id: 'reset-peaks',
    label: 'Reset peak trackers',
    command: 'R',
    category: 'diagnostics',
    description: 'ASCII R — reset peak counters used by I.',
  },
  {
    id: 'axis-params',
    label: 'FFB axis params (M)',
    command: 'M',
    category: 'diagnostics',
    description: 'ASCII M — maxtorque, fxratio, range, effective Nm. Alternate readout of axis.*.',
  },
];

export function commandsByCategory(category: CommandCategory): BoardCommand[] {
  return boardCommands.filter((command) => command.category === category);
}
