/**
 * Defaults, examples and display ranges aligned with odrive-wheel.html FIELD_RANGE,
 * setup wizard (FORM_*), and Odrive-Wheel firmware protocol (see docs/firmware-api.md).
 */

export const fieldRanges: Record<string, string> = {
  'config.brake_resistance': '0.05–10 Ω',
  'config.dc_bus_undervoltage_trip_level': '5–30 V',
  'config.dc_bus_overvoltage_trip_level': '20–60 V',
  'config.dc_bus_overvoltage_ramp_start': '15–55 V',
  'config.dc_bus_overvoltage_ramp_end': '15–60 V',
  'config.dc_max_positive_current': '0–100 A',
  'config.dc_max_negative_current': '-100..0 A',
  'config.max_regen_current': '0–100 A',
  'sys.vbusdiv': '1–50',
  'axis0.requested_state': '1–16',
  'axis0.motor.config.pole_pairs': '1–32',
  'axis0.motor.config.torque_constant': '0.001–10 Nm/A',
  'axis0.motor.config.calibration_current': '1–60 A',
  'axis0.motor.config.resistance_calib_max_voltage': '0.5–20 V',
  'axis0.motor.config.requested_current_range': '5–80 A',
  'axis0.motor.config.current_control_bandwidth': '50–2000 rad/s',
  'axis0.motor.config.current_control_deadband': '0–0.5 A (0.02–0.20 típico)',
  'axis0.motor.config.current_lim': '0–80 A',
  'axis0.encoder.config.cpr': '1–1000000',
  'axis0.encoder.config.direction': '-1 ou 1',
  'axis0.encoder.config.bandwidth': '50–2000 Hz',
  'axis0.encoder.config.abs_spi_cs_gpio_pin': '0–16 (0=off)',
  'axis0.controller.config.pos_gain': '0.1–500',
  'axis0.controller.config.vel_gain': '0.001–10',
  'axis0.controller.config.vel_integrator_gain': '0.001–10',
  'axis0.controller.config.inertia': '0–10 kg·m²',
  'axis0.controller.config.vel_limit': '0.01–1000 turn/s',
  'axis0.controller.config.vel_limit_tolerance': '1.0–5.0',
  'axis.range': '90–3600°',
  'axis.maxtorque': '0.1–25 Nm',
  'axis.fxratio': '0.0–1.0',
  'axis.idlespring': '0–255',
  'axis.axisdamper': '0–255',
  'axis.axisinertia': '0–255',
  'axis.axisfriction': '0–255',
  'axis.esgain': '0–255',
  'axis.esdamp': '0–255',
  'axis.maxtorquerate': '0–65535',
  'axis.expo': '-32767..32767',
  'axis.exposcale': '1–255',
  'axis.zeroofs': '±3600°',
  'axis.gpiofilt': '0 ou 1',
  'axis.gpiofiltf': '0.5–500 Hz',
  'axis.gpioautocal': '0 ou 1',
  'fx.master': '0–255',
  'fx.spring': '0–255',
  'fx.damper': '0–255',
  'fx.friction': '0–255',
  'fx.inertia': '0–255',
  'fx.filterCfFreq': '1–500 Hz',
  'fx.filterCfQ': '1–500 (×0.01)',
  'fx.filterFrFreq': '1–500 Hz',
  'fx.filterFrQ': '1–500 (×0.01)',
  'fx.filterDaFreq': '1–500 Hz',
  'fx.filterDaQ': '1–500 (×0.01)',
  'fx.filterInFreq': '1–500 Hz',
  'fx.filterInQ': '1–500 (×0.01)',
};

/** Firmware boot RAM or setup-wizard recommended starting points for Odrive-Wheel. */
export const fieldDefaults: Record<string, string> = {
  'config.brake_resistance': '2',
  'config.enable_brake_resistor': 'true',
  'config.dc_bus_undervoltage_trip_level': '8',
  'config.dc_bus_overvoltage_trip_level': '28',
  'config.dc_bus_overvoltage_ramp_start': '25',
  'config.dc_bus_overvoltage_ramp_end': '27',
  'config.dc_max_positive_current': '25',
  'config.dc_max_negative_current': '-15',
  'config.max_regen_current': '0',
  'sys.vbusdiv': '19',
  'axis0.requested_state': '1',
  'axis0.config.startup_closed_loop_control': 'false',
  'axis0.config.startup_motor_calibration': 'false',
  'axis0.config.startup_encoder_offset_calibration': 'false',
  'axis0.config.startup_encoder_index_search': 'false',
  'axis0.motor.config.motor_type': '0',
  'axis0.motor.config.pole_pairs': '4',
  'axis0.motor.config.torque_constant': '0.87',
  'axis0.motor.config.current_lim': '20',
  'axis0.motor.config.calibration_current': '5',
  'axis0.motor.config.resistance_calib_max_voltage': '12',
  'axis0.motor.config.requested_current_range': '25',
  'axis0.motor.config.current_control_bandwidth': '200',
  'axis0.motor.config.current_control_deadband': '0.1',
  'axis0.motor.config.pre_calibrated': 'false',
  'axis0.encoder.config.mode': '257',
  'axis0.encoder.config.cpr': '16384',
  'axis0.encoder.config.direction': '1',
  'axis0.encoder.config.bandwidth': '200',
  'axis0.encoder.config.use_index': 'false',
  'axis0.encoder.config.abs_spi_cs_gpio_pin': '7',
  'axis0.encoder.config.pre_calibrated': 'false',
  'axis0.controller.config.control_mode': '1',
  'axis0.controller.config.input_mode': '1',
  'axis0.controller.config.enable_vel_limit': 'false',
  'axis0.controller.config.enable_overspeed_error': 'false',
  'axis0.controller.config.enable_torque_mode_vel_limit': 'false',
  'axis0.controller.config.anticogging.anticogging_enabled': 'false',
  'axis0.controller.config.anticogging.pre_calibrated': 'false',
  'axis.range': '900',
  'axis.maxtorque': '5',
  'axis.fxratio': '0.8',
  'axis.invert': 'false',
  'axis.ffbinvert': 'false',
  'axis.idlespring': '0',
  'axis.axisdamper': '0',
  'axis.axisinertia': '0',
  'axis.axisfriction': '0',
  'axis.esgain': '0',
  'axis.esdamp': '15',
  'axis.maxtorquerate': '0',
  'axis.expo': '0',
  'axis.exposcale': '100',
  'axis.zeroofs': '0',
  'axis.gpiofilt': 'false',
  'axis.gpiofiltf': '60',
  'axis.gpioautocal': 'false',
  'fx.master': '255',
  'fx.spring': '64',
  'fx.damper': '64',
  'fx.friction': '254',
  'fx.inertia': '127',
  'fx.filterCfFreq': '200',
  'fx.filterCfQ': '70',
  'fx.filterFrFreq': '50',
  'fx.filterFrQ': '20',
  'fx.filterDaFreq': '30',
  'fx.filterDaQ': '20',
  'fx.filterInFreq': '30',
  'fx.filterInQ': '20',
};

/** Practical Odrive-Wheel examples (MKS 24 V, servo 18 Nm, sim-racing FFB). */
export const fieldExamples: Record<string, string> = {
  'config.brake_resistance': '2.0',
  'config.dc_bus_overvoltage_trip_level': '28',
  'config.dc_bus_undervoltage_trip_level': '8',
  'config.dc_bus_overvoltage_ramp_start': '25',
  'config.dc_bus_overvoltage_ramp_end': '27',
  'config.dc_max_positive_current': '25',
  'config.dc_max_negative_current': '-15',
  'sys.vbusdiv': '19',
  'axis0.requested_state': '8',
  'axis0.motor.config.pole_pairs': '4',
  'axis0.motor.config.torque_constant': '0.87',
  'axis0.motor.config.current_lim': '20',
  'axis0.motor.config.calibration_current': '5',
  'axis0.motor.config.resistance_calib_max_voltage': '12',
  'axis0.motor.config.requested_current_range': '25',
  'axis0.motor.config.current_control_bandwidth': '200',
  'axis0.motor.config.current_control_deadband': '0.1',
  'axis0.encoder.config.cpr': '16384',
  'axis0.encoder.config.mode': '257',
  'axis0.controller.config.vel_limit': '10',
  'axis.range': '900',
  'axis.maxtorque': '3',
  'axis.fxratio': '0.75',
  'axis.idlespring': '15',
  'axis.axisdamper': '8',
  'axis.axisinertia': '10',
  'axis.esgain': '60',
  'axis.esdamp': '15',
  'axis.maxtorquerate': '4',
  'fx.filterCfFreq': '120',
  'fx.filterCfQ': '70',
};
