import { GPIO_CHANNELS, gpioIsAnalog, gpioMcuPin } from '../../domain/gpioPinout';

export type FieldType = 'float' | 'int' | 'bool' | 'enum' | 'command' | 'readonly';
export type FieldProtocol = 'odrive' | 'openffboard';

export interface FieldOption {
  value: string;
  label: string;
}

export interface ConfigField {
  path: string;
  label: string;
  type: FieldType;
  protocol: FieldProtocol;
  description: string;
  min?: number;
  max?: number;
  step?: number;
  unit?: string;
  defaultValue?: string;
  exampleValue?: string;
  help?: string;
  caution?: string;
  options?: FieldOption[];
  readonly?: boolean;
  /** Show in config editor even when readonly (e.g. axis current_state). */
  configVisible?: boolean;
  groupId?: string;
}

export interface ConfigGroup {
  id: string;
  title: string;
  description: string;
  fields: ConfigField[];
}

const boolOptions: FieldOption[] = [
  { value: 'true', label: 'True' },
  { value: 'false', label: 'False' },
];

const controlModeOptions: FieldOption[] = [
  { value: '0', label: 'Voltage' },
  { value: '1', label: 'Torque' },
  { value: '2', label: 'Velocity' },
  { value: '3', label: 'Position' },
];

const inputModeOptions: FieldOption[] = [
  { value: '0', label: 'Inactive' },
  { value: '1', label: 'Passthrough' },
  { value: '2', label: 'Velocity ramp' },
  { value: '3', label: 'Position filter' },
  { value: '5', label: 'Torque ramp' },
];

const encoderModeOptions: FieldOption[] = [
  { value: '0', label: 'Incremental (ABZ)' },
  { value: '1', label: 'Hall (ODrive stock)' },
  { value: '257', label: 'SPI ABS AMS (AS5047 / MKS)' },
  { value: '258', label: 'SPI ABS CUI (ODrive stock)' },
  { value: '259', label: 'SPI ABS AEAT (ODrive stock)' },
  { value: '260', label: 'SPI ABS RLS (ODrive stock)' },
  { value: '261', label: 'SPI ABS MagnTek (MT6835 / 21-bit)' },
];

const motorTypeOptions: FieldOption[] = [
  { value: '0', label: 'High current BLDC' },
  { value: '2', label: 'Gimbal' },
  { value: '3', label: 'ACIM (not used on FFB wheel)' },
];

/** ODrive axis state codes (requested_state command / current_state live). */
export const axisStateOptions: FieldOption[] = [
  { value: '0', label: 'Undefined (no pending request)' },
  { value: '1', label: 'IDLE' },
  { value: '2', label: 'Startup sequence' },
  { value: '3', label: 'Full calibration sequence' },
  { value: '4', label: 'Motor calibration' },
  { value: '5', label: 'Encoder calibration' },
  { value: '6', label: 'Encoder index search' },
  { value: '7', label: 'Encoder offset calibration' },
  { value: '8', label: 'Closed-loop control' },
  { value: '9', label: 'Lockin spin' },
  { value: '10', label: 'Encoder direction find' },
  { value: '11', label: 'Homing' },
];

const gpioModeOptions: FieldOption[] = [
  { value: '0', label: 'Disabled' },
  { value: '1', label: 'Button' },
  { value: '2', label: 'Analog axis' },
  { value: '3', label: 'Zero wheel' },
];

const gpioDigitalModeOptions: FieldOption[] = [
  { value: '0', label: 'Disabled' },
  { value: '1', label: 'Button' },
  { value: '3', label: 'Zero wheel' },
];

function gpioChannelFields(gpio: number): ConfigField[] {
  const pin = gpioMcuPin(gpio);
  const analog = gpioIsAnalog(gpio);
  const fields: ConfigField[] = [
    {
      path: `gpio.${gpio}.mode`,
      label: `GPIO ${gpio} mode (${pin})`,
      type: 'enum',
      protocol: 'openffboard',
      options: analog ? gpioModeOptions : gpioDigitalModeOptions,
      description: analog
        ? `MKS ${pin} (ADC). 0=off, 1=HID button 0–63, 2=HID axis Rx/Ry/Rz/Slider, 3=zero-wheel (axis.zeroenc in RAM until sys.save!).`
        : `MKS ${pin} digital-only (no ADC). 0=off, 1=HID button, 3=zero-wheel. Analog mode is rejected by firmware.`,
    },
    {
      path: `gpio.${gpio}.idx`,
      label: `GPIO ${gpio} index`,
      type: 'int',
      protocol: 'openffboard',
      min: 0,
      max: 63,
      step: 1,
      description: analog
        ? 'Button bit 0–63, or analog HID axis 0–3 (Rx/Ry/Rz/Slider) when mode=2.'
        : 'HID button bit 0–63 (digital pin — no analog axis).',
    },
    {
      path: `gpio.${gpio}.invert`,
      label: `GPIO ${gpio} invert`,
      type: 'bool',
      protocol: 'openffboard',
      options: boolOptions,
      description: 'Inverts button polarity or analog direction.',
    },
    {
      path: `gpio.${gpio}.cur`,
      label: `GPIO ${gpio} raw`,
      type: 'readonly',
      protocol: 'openffboard',
      readonly: true,
      description: analog
        ? 'Live raw ADC (0–4095) or digital 0/1. 65535 = disabled.'
        : 'Live digital 0/1. 65535 = disabled.',
    },
  ];
  if (analog) {
    fields.splice(3, 0,
      {
        path: `gpio.${gpio}.amin`,
        label: `GPIO ${gpio} analog min`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 4095,
        step: 1,
        description: 'Raw ADC minimum for analog axis calibration (mode=2 only).',
      },
      {
        path: `gpio.${gpio}.amax`,
        label: `GPIO ${gpio} analog max`,
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 4095,
        step: 1,
        description: 'Raw ADC maximum for analog axis calibration (mode=2 only).',
      },
    );
    fields.push({
      path: `gpio.${gpio}.filt`,
      label: `GPIO ${gpio} filtered`,
      type: 'readonly',
      protocol: 'openffboard',
      readonly: true,
      description: 'Last Biquad-filtered ADC value when axis.gpiofilt is on. 65535 = N/A.',
    });
  }
  return fields;
}

export const configGroups: ConfigGroup[] = [
  {
    id: 'psu',
    title: 'PSU / Brake',
    description: 'Power supply and brake resistor limits from the ODrive config.',
    fields: [
      {
        path: 'vbus_voltage',
        label: 'VBUS voltage',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Live DC bus voltage reported by the board.',
      },
      {
        path: 'ibus',
        label: 'IBUS',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Live DC bus current.',
      },
      {
        path: 'brake_resistor_current',
        label: 'Brake resistor current',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Estimated brake resistor current for regen/power monitoring.',
      },
      {
        path: 'config.dc_bus_overvoltage_trip_level',
        label: 'Overvoltage trip',
        type: 'float',
        protocol: 'odrive',
        min: 20,
        max: 60,
        step: 0.1,
        description: 'Bus voltage that triggers an overvoltage fault. Set 2–4 V above PSU nominal.',
      },
      {
        path: 'config.dc_bus_undervoltage_trip_level',
        label: 'Undervoltage trip',
        type: 'float',
        protocol: 'odrive',
        min: 5,
        max: 30,
        step: 0.1,
        description: 'Bus voltage that triggers an undervoltage fault. Set just below minimum supply voltage.',
      },
      {
        path: 'config.brake_resistance',
        label: 'Brake resistance',
        type: 'float',
        protocol: 'odrive',
        min: 0.05,
        max: 10,
        step: 0.1,
        description: 'Physical brake resistor value in ohms. Must match exactly — verify with a multimeter.',
      },
      {
        path: 'config.enable_brake_resistor',
        label: 'Enable brake resistor',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enables the brake resistor for regen energy dissipation. Required for sustained FFB sessions.',
      },
      {
        path: 'config.dc_bus_overvoltage_ramp_start',
        label: 'Brake ramp start',
        type: 'float',
        protocol: 'odrive',
        min: 15,
        max: 55,
        step: 0.1,
        description: 'Bus voltage where brake resistor duty begins ramping up. Must be < ramp_end.',
      },
      {
        path: 'config.dc_bus_overvoltage_ramp_end',
        label: 'Brake ramp end',
        type: 'float',
        protocol: 'odrive',
        min: 15,
        max: 60,
        step: 0.1,
        description: 'Bus voltage where brake resistor reaches full 100 % duty. Set = trip_level − 1 V.',
      },
      {
        path: 'config.dc_max_positive_current',
        label: 'PSU current max',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 100,
        step: 0.1,
        description: 'Maximum current the ODrive draws from the power supply. Set ≤ PSU rated current.',
      },
      {
        path: 'config.dc_max_negative_current',
        label: 'Regen current max',
        type: 'float',
        protocol: 'odrive',
        min: -100,
        max: 0,
        step: 0.1,
        description: 'Maximum regen current pushed back into the supply (keep negative). Use −0.1 for non-regen PSUs.',
      },
      {
        path: 'config.max_regen_current',
        label: 'Max regen current',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 100,
        step: 0.1,
        description: 'Maximum regen current into the DC bus. Set 0 when using a non-regen PSU.',
      },
      {
        path: 'sys.vbusdiv',
        label: 'VBUS divider',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 50,
        step: 1,
        defaultValue: '19',
        exampleValue: '19',
        description:
          '⚠ Hardware parameter. ADC voltage divider ratio (not volts). Wrong value = incorrect VBUS readings and broken protection thresholds. MKS XDrive Mini default is 19 — calibrate in Setup if readings disagree with a multimeter.',
      },
    ],
  },
  {
    id: 'axis',
    title: 'Axis 0',
    description: 'Axis state, startup behavior, and closed-loop defaults.',
    fields: [
      {
        path: 'axis0.current_state',
        label: 'Current state',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        configVisible: true,
        description:
          'Live ODrive axis state. When FFB is active this should read 8 (closed-loop). Use this — not requested_state — to know what the axis is doing.',
      },
      {
        path: 'axis0.requested_state',
        label: 'Requested state',
        type: 'enum',
        protocol: 'odrive',
        options: axisStateOptions,
        description:
          'Write-only state command. After the axis reaches the target, ODrive often resets this to 0 (no pending request) while current_state stays at the active state (e.g. 8). 1 = IDLE, 8 = closed-loop. Never send 3 with the wheel mounted.',
      },
      {
        path: 'axis0.config.startup_closed_loop_control',
        label: 'Startup closed loop',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Auto-enters closed-loop after boot. Only enable after motor and encoder are pre_calibrated.',
      },
      {
        path: 'axis0.config.startup_motor_calibration',
        label: 'Startup motor cal',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Run motor R/L calibration on boot. Set false after calibrating once and saving — use pre_calibrated instead.',
      },
      {
        path: 'axis0.config.startup_encoder_offset_calibration',
        label: 'Startup encoder cal',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Run encoder offset cal on boot. Set false after calibrating once and saving — use pre_calibrated instead.',
      },
      {
        path: 'axis0.config.startup_encoder_index_search',
        label: 'Startup index search',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Search encoder Z index on boot. Only for incremental encoders with index wired.',
      },
    ],
  },
  {
    id: 'motor',
    title: 'Motor',
    description: 'Motor calibration, torque constant, and current limits.',
    fields: [
      {
        path: 'axis0.motor.config.current_lim',
        label: 'Current limit',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 80,
        step: 0.1,
        description: '⚠ Safety-critical. Max phase current = max torque. Set ≤ motor rated current. Formula: current_lim = max_torque_Nm ÷ torque_constant.',
      },
      {
        path: 'axis0.motor.config.motor_type',
        label: 'Motor type',
        type: 'enum',
        protocol: 'odrive',
        options: motorTypeOptions,
        description: 'Motor construction. High-current BLDC (0) for FFB wheels. Gimbal is rare. ACIM is stock ODrive and not used on this base.',
      },
      {
        path: 'axis0.motor.config.pole_pairs',
        label: 'Pole pairs',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 32,
        step: 1,
        description: '⚠ Must be exact. Count rotor magnets ÷ 2. Wrong value = failed calibration or erratic torque.',
      },
      {
        path: 'axis0.motor.config.calibration_current',
        label: 'Calibration current',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 60,
        step: 0.1,
        description: 'Current used during R/L measurement. Set to ~25 % of current_lim. Too low = inaccurate calibration.',
      },
      {
        path: 'axis0.motor.config.resistance_calib_max_voltage',
        label: 'R calib max voltage',
        type: 'float',
        protocol: 'odrive',
        min: 0.5,
        max: 20,
        step: 0.1,
        description: 'Voltage ceiling during resistance measurement. Raise to 6–8 V if calibration fails on high-resistance motors.',
      },
      {
        path: 'axis0.motor.config.torque_constant',
        label: 'Torque constant (Kt)',
        type: 'float',
        protocol: 'odrive',
        min: 0.001,
        max: 10,
        step: 0.001,
        description: '⚠ Critical. Nm/A ratio used to convert torque commands to phase current. Kt = rated_Nm ÷ rated_A or 8.27 ÷ motor_kv.',
      },
      {
        path: 'axis0.motor.config.current_control_bandwidth',
        label: 'Current bandwidth',
        type: 'float',
        protocol: 'odrive',
        min: 50,
        max: 2000,
        step: 1,
        description: 'Current loop speed in rad/s. Higher = crisper FFB feel. Too high = audible oscillation. Start at 100, increase carefully.',
      },
      {
        path: 'axis0.motor.config.requested_current_range',
        label: 'Requested current range',
        type: 'float',
        protocol: 'odrive',
        min: 1,
        max: 80,
        step: 0.1,
        description: 'ADC current sense range in amps. Set slightly above current_lim.',
      },
      {
        path: 'axis0.motor.config.phase_resistance',
        label: 'Phase resistance',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured phase resistance from motor calibration (Ω).',
      },
      {
        path: 'axis0.motor.config.phase_inductance',
        label: 'Phase inductance',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured phase inductance from motor calibration (H).',
      },
      {
        path: 'axis0.motor.config.current_control_deadband',
        label: 'Current deadband',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 0.5,
        step: 0.01,
        description: 'Odrive-Wheel mod: dead-band on current PI (A). Default 0.1 (100 mA). Useful 0.02–0.20 to kill idle hum.',
      },
      {
        path: 'axis0.motor.config.pre_calibrated',
        label: 'Motor pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skip R/L calibration on boot. Only set true after a successful calibration with valid R/L measurements.',
      },
      {
        path: 'axis0.motor.is_calibrated',
        label: 'Motor calibrated',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'True after resistance and inductance calibration succeeds.',
      },
      {
        path: 'axis0.motor.current_control.Iq_measured',
        label: 'Iq measured',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Measured quadrature current, useful for saturation and FFB load monitoring.',
      },
    ],
  },
  {
    id: 'encoder',
    title: 'Encoder',
    description: 'Encoder mode, CPR, direction, and calibration flags.',
    fields: [
      {
        path: 'axis0.encoder.config.mode',
        label: 'Encoder mode',
        type: 'enum',
        protocol: 'odrive',
        options: encoderModeOptions,
        description: 'Encoder type. MKS onboard is SPI ABS AMS (257) / CPR 16384. Incremental (0) is ABZ. Hall and other SPI IDs are stock ODrive — not the MKS path.',
      },
      {
        path: 'axis0.encoder.config.cpr',
        label: 'CPR',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 1000000,
        step: 1,
        description: '⚠ Must match encoder spec (counts/rev = lines/rev × 4 for quadrature). Wrong CPR = incorrect speed and position.',
      },
      {
        path: 'axis0.encoder.config.direction',
        label: 'Direction',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        configVisible: true,
        description:
          'READONLY — set by motor/encoder calibration (1 or −1). Do not edit manually; wrong value breaks FOC. For user/game direction use axis.invert (FFB Wheel). To detect: calibration state 10 (encoder dir find).',
      },
      {
        path: 'axis0.encoder.config.bandwidth',
        label: 'Encoder bandwidth',
        type: 'float',
        protocol: 'odrive',
        min: 50,
        max: 2000,
        step: 1,
        description: 'PLL position/velocity estimator speed. Higher = better FFB tracking. Reduce only if encoder signal is noisy.',
      },
      {
        path: 'axis0.encoder.config.use_index',
        label: 'Use index Z',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enable when encoder has a Z pulse wired. ODrive searches for it on startup before entering closed-loop.',
      },
      {
        path: 'axis0.encoder.config.use_index_offset',
        label: 'Use index offset',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Apply index_offset when the Z pulse is detected.',
      },
      {
        path: 'axis0.encoder.config.index_offset',
        label: 'Index offset',
        type: 'float',
        protocol: 'odrive',
        step: 0.0001,
        description: 'Offset in turns applied at Z pulse — defines mechanical zero relative to index. Use Capture mechanical center on Calibration tab.',
      },
      {
        path: 'axis0.encoder.config.abs_spi_cs_gpio_pin',
        label: 'ABS SPI CS pin',
        type: 'int',
        protocol: 'odrive',
        min: 0,
        max: 15,
        step: 1,
        description: 'GPIO chip-select for SPI absolute encoders (AS5047 default: 7 on MKS).',
      },
      {
        path: 'axis0.encoder.config.pre_calibrated',
        label: 'Pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skip encoder offset calibration on boot. Only enable after at least one successful calibration cycle.',
      },
      {
        path: 'axis0.encoder.config.phase_offset',
        label: 'Phase offset',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Electrical offset (counts) from encoder cal state 7. READONLY — saved to NVM only via toolbar Save.',
      },
      {
        path: 'axis0.encoder.config.phase_offset_float',
        label: 'Phase offset float',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Fine electrical offset (rad) from encoder cal. READONLY — NVM via toolbar Save.',
      },
      {
        path: 'axis0.encoder.is_ready',
        label: 'Encoder ready',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'True when ODrive has a valid encoder estimate.',
      },
    ],
  },
  {
    id: 'controller',
    title: 'Controller',
    description: 'Controller mode and torque-mode parameters for FFB operation.',
    fields: [
      {
        path: 'axis0.controller.config.control_mode',
        label: 'Control mode',
        type: 'enum',
        protocol: 'odrive',
        options: controlModeOptions,
        description: '⚠ Must be Torque (1) for FFB. Other modes are incompatible with direct torque commands.',
      },
      {
        path: 'axis0.controller.config.input_mode',
        label: 'Input mode',
        type: 'enum',
        protocol: 'odrive',
        options: inputModeOptions,
        description: '⚠ Must be Passthrough (1) for FFB. Routes input_torque directly to the motor with minimum latency.',
      },
      {
        path: 'axis0.controller.config.vel_limit',
        label: 'Velocity limit',
        type: 'float',
        protocol: 'odrive',
        min: 0.01,
        max: 1000,
        step: 0.1,
        description: 'Velocity ceiling in turns/s. Only applies when enable_vel_limit is true. Typically disabled for FFB.',
      },
      {
        path: 'axis0.controller.config.enable_vel_limit',
        label: 'Enable vel limit',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: '⚠ Keep false for FFB. Enabling suppresses game forces when the wheel spins fast.',
      },
      {
        path: 'axis0.controller.config.enable_overspeed_error',
        label: 'Overspeed error',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: '⚠ Keep false for FFB. Enabling trips the axis into error during fast steering inputs, freezing the motor.',
      },
      {
        path: 'axis0.controller.config.enable_torque_mode_vel_limit',
        label: 'Torque mode vel clamp',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: '⚠ Must be false for FFB. When true, ODrive injects opposing forces above vel_limit, fighting game effects.',
      },
      {
        path: 'axis0.controller.config.pos_gain',
        label: 'Position gain',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 500,
        step: 0.1,
        description: 'Position PID proportional gain. Ignored in TORQUE mode.',
      },
      {
        path: 'axis0.controller.config.vel_gain',
        label: 'Velocity gain',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 10,
        step: 0.001,
        description: 'Velocity PID proportional gain. Ignored as PID in TORQUE mode; used only if torque-mode vel clamp is enabled.',
      },
      {
        path: 'axis0.controller.config.vel_integrator_gain',
        label: 'Vel integrator gain',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 10,
        step: 0.001,
        description: 'Velocity integrator gain. Ignored in TORQUE mode.',
      },
      {
        path: 'axis0.controller.config.inertia',
        label: 'Inertia',
        type: 'float',
        protocol: 'odrive',
        min: 0,
        max: 10,
        step: 0.001,
        description: 'Load inertia feed-forward (kg·m²). Ignored in TORQUE mode.',
      },
      {
        path: 'axis0.controller.config.anticogging.anticogging_enabled',
        label: 'Anticogging enabled',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Apply anticogging torque map when pre_calibrated is true.',
      },
      {
        path: 'axis0.controller.config.anticogging.pre_calibrated',
        label: 'Anticogging pre-calibrated',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Skip anticogging calibration on boot. Set after successful axis.anticogcal! run.',
      },
      {
        path: 'axis0.controller.config.anticogging.index',
        label: 'Anticogging index',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Progress index during anticogging calibration (0–3600).',
      },
      {
        path: 'axis0.controller.input_torque',
        label: 'Input torque',
        type: 'readonly',
        protocol: 'odrive',
        readonly: true,
        description: 'Current torque setpoint written by the FFB bridge.',
      },
    ],
  },
  {
    id: 'ffb-wheel',
    title: 'FFB Wheel',
    description: 'OpenFFBoard-style wheel parameters persisted by sys.save.',
    fields: [
      {
        path: 'axis.range',
        label: 'Range',
        type: 'float',
        protocol: 'openffboard',
        min: 90,
        max: 2520,
        step: 1,
        description: 'Wheel lock-to-lock angle in degrees. Match your simulator steering lock setting for correct 1:1 ratio.',
      },
      {
        path: 'axis.maxtorque',
        label: 'Max torque',
        type: 'float',
        protocol: 'openffboard',
        min: 0.1,
        max: 25,
        step: 0.1,
        description: '⚠ Torque ceiling. HID full-scale maps to this Nm. Set = current_lim × torque_constant. See TorqueCapAdvisor.',
      },
      {
        path: 'axis.fxratio',
        label: 'FX ratio',
        type: 'float',
        protocol: 'openffboard',
        min: 0,
        max: 1,
        step: 0.01,
        description: 'Global FFB strength multiplier (0–1). Master volume for FFB without changing motor limits. 0.75 is a safe starting point.',
      },
      {
        path: 'axis.invert',
        label: 'Invert wheel',
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        description: 'Inverts wheel axis position / HID IN direction for the game and app telemetry.',
      },
      {
        path: 'axis.ffbinvert',
        label: 'Invert FFB force',
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        description: 'Inverts FFB force direction (game torque / HID OUT). Independent of wheel axis inversion.',
      },
      {
        path: 'axis.idlespring',
        label: 'Idle spring',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Centering spring active when game FFB is off (menus, paused). 0 = free wheel. ~15 = gentle return-to-center.',
      },
      {
        path: 'axis.axisdamper',
        label: 'Axis damper',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active velocity resistance (like a hydraulic damper). 0 = off. 8–20 = subtle weight. Independent of game.',
      },
      {
        path: 'axis.axisinertia',
        label: 'Axis inertia',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active acceleration resistance (flywheel simulation). 0 = off. 5–20 = realistic mass without killing responsiveness.',
      },
      {
        path: 'axis.axisfriction',
        label: 'Axis friction',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Always-active constant friction (stiction). 0 = off. Use sparingly — high values mask fine FFB textures from the game.',
      },
      {
        path: 'axis.esgain',
        label: 'End-stop spring',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Virtual lock strength when wheel reaches ±range. 0 = no soft stop (dangerous). 40–100 = firm wall.',
      },
      {
        path: 'axis.esdamp',
        label: 'End-stop damper',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Damping at the virtual lock to prevent wheel bounce. Increase if wheel rebounds off the end-stop.',
      },
      {
        path: 'axis.maxtorquerate',
        label: 'Torque slew limit',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 65535,
        step: 1,
        description: 'Max torque change per ms. 0 = disabled (sharpest response). 2–6 smooths abrupt force transitions. High values add latency.',
      },
      {
        path: 'axis.expo',
        label: 'Expo',
        type: 'int',
        protocol: 'openffboard',
        min: -32767,
        max: 32767,
        step: 1,
        description: 'Non-linear HID position curve. 0 = linear. Positive = more center sensitivity. Does not affect FFB forces.',
      },
      {
        path: 'axis.exposcale',
        label: 'Expo scale',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 255,
        step: 1,
        description: 'Divisor for expo curve strength. Higher = softer expo effect. 1 = full expo at the configured axis.expo value.',
      },
      {
        path: 'axis.zeroofs',
        label: 'Zero offset',
        type: 'float',
        protocol: 'openffboard',
        min: -3600,
        max: 3600,
        step: 0.001,
        unit: 'deg',
        description: 'Persistent virtual center offset in degrees. Set to 0 to undo a software center shift. Persists via sys.save!.',
      },
    ],
  },
  {
    id: 'ffb-effects',
    title: 'FFB Effects',
    description: 'Master and per-effect gains from the EffectsCalculator.',
    fields: [
      {
        path: 'fx.master',
        label: 'Master gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Global gain applied to ALL effects. 255 = 100 %. Multiplicative with axis.fxratio.',
      },
      {
        path: 'fx.spring',
        label: 'Spring gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for spring condition effects (centering, lane-keep). 0 = disables spring forces from games.',
      },
      {
        path: 'fx.damper',
        label: 'Damper gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for damper condition effects (velocity resistance). High = heavy wheel. Typical 80–180.',
      },
      {
        path: 'fx.friction',
        label: 'Friction gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for friction condition effects (constant resistance). High values dull fine road texture. Typical 50–150.',
      },
      {
        path: 'fx.inertia',
        label: 'Inertia gain',
        type: 'int',
        protocol: 'openffboard',
        min: 0,
        max: 255,
        step: 1,
        description: 'Scale for inertia condition effects (mass simulation). High = sluggish, heavy wheel. Typical 50–150.',
      },
    ],
  },
  {
    id: 'ffb-filters',
    title: 'FFB Filters',
    description: 'Biquad low-pass filter parameters exposed by EffectsCalculator.',
    fields: [
      {
        path: 'fx.filterCfFreq',
        label: 'CF filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Low-pass cutoff for constant force (main FFB channel). Firmware default 200 Hz. Range 1–500 Hz.',
      },
      {
        path: 'fx.filterCfQ',
        label: 'CF filter Q',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Q stored as integer ×0.01 (70 = Q 0.70 Butterworth). Not 0.707 in this field — enter 70.',
      },
      {
        path: 'fx.filterDaFreq',
        label: 'Damper filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Low-pass cutoff for damper effects. Default 30 Hz.',
      },
      {
        path: 'fx.filterDaQ',
        label: 'Damper filter Q',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Q stored as integer ×0.01 (70 = Q 0.70 Butterworth). Default 20.',
      },
      {
        path: 'fx.filterFrFreq',
        label: 'Friction filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Low-pass cutoff for friction effects. Default 50 Hz.',
      },
      {
        path: 'fx.filterFrQ',
        label: 'Friction filter Q',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Q stored as integer ×0.01 (70 = Q 0.70 Butterworth). Default 20.',
      },
      {
        path: 'fx.filterInFreq',
        label: 'Inertia filter frequency',
        type: 'float',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Low-pass cutoff for inertia effects. Default 30 Hz.',
      },
      {
        path: 'fx.filterInQ',
        label: 'Inertia filter Q',
        type: 'int',
        protocol: 'openffboard',
        min: 1,
        max: 500,
        step: 1,
        description: 'Q stored as integer ×0.01 (70 = Q 0.70 Butterworth). Default 20.',
      },
    ],
  },
  {
    id: 'motor-thermistor',
    title: 'Motor thermistor',
    description: 'Offboard NTC temperature monitoring and polynomial coefficients.',
    fields: [
      {
        path: 'axis0.motor.motor_thermistor.config.enabled',
        label: 'Thermistor enabled',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Enable motor temperature monitoring via external NTC. Use NTC calculator for polynomial coefficients.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.gpio_pin',
        label: 'NTC GPIO pin',
        type: 'int',
        protocol: 'odrive',
        min: 1,
        max: 8,
        step: 1,
        description: 'GPIO for NTC analog input. Requires external 10kΩ pull-up to 3.3V.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.temp_limit_lower',
        label: 'Motor temp limit lower',
        type: 'float',
        protocol: 'odrive',
        min: 50,
        max: 120,
        step: 1,
        unit: '°C',
        description: 'Motor temperature (°C) where current_lim begins to be reduced linearly.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.temp_limit_upper',
        label: 'Motor temp limit upper',
        type: 'float',
        protocol: 'odrive',
        min: 60,
        max: 150,
        step: 1,
        unit: '°C',
        description: 'Motor temperature (°C) where current_lim reaches zero and MOTOR_THERMISTOR_OVER_TEMP triggers.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_0',
        label: 'Poly coefficient 0',
        type: 'float',
        protocol: 'odrive',
        description: 'Highest-order coefficient of T(V) polynomial. Use NTC calculator.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_1',
        label: 'Poly coefficient 1',
        type: 'float',
        protocol: 'odrive',
        description: 'Polynomial coefficient c1.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_2',
        label: 'Poly coefficient 2',
        type: 'float',
        protocol: 'odrive',
        description: 'Polynomial coefficient c2.',
      },
      {
        path: 'axis0.motor.motor_thermistor.config.poly_coefficient_3',
        label: 'Poly coefficient 3',
        type: 'float',
        protocol: 'odrive',
        description: 'Lowest-order coefficient c3.',
      },
    ],
  },
  {
    id: 'fet-thermistor',
    title: 'FET thermistor',
    description: 'Onboard gate-driver / MOSFET temperature limits (ODrive 0.5.6 — replaces legacy inverter_temp_limit).',
    fields: [
      {
        path: 'axis0.motor.fet_thermistor.config.enabled',
        label: 'FET thermistor enabled',
        type: 'bool',
        protocol: 'odrive',
        options: boolOptions,
        description: 'Monitor onboard FET temperature. Reduces current_lim between temp_limit_lower and temp_limit_upper.',
      },
      {
        path: 'axis0.motor.fet_thermistor.config.temp_limit_lower',
        label: 'FET temp limit lower',
        type: 'float',
        protocol: 'odrive',
        min: 50,
        max: 120,
        step: 1,
        unit: '°C',
        description: 'FET temperature (°C) where current_lim begins to be reduced linearly. Default 80–100 °C.',
      },
      {
        path: 'axis0.motor.fet_thermistor.config.temp_limit_upper',
        label: 'FET temp limit upper',
        type: 'float',
        protocol: 'odrive',
        min: 60,
        max: 125,
        step: 1,
        unit: '°C',
        description: 'FET temperature (°C) where current_lim reaches zero and FET_THERMISTOR_OVER_TEMP triggers.',
      },
    ],
  },
  {
    id: 'inputs',
    title: 'Inputs',
    description: 'GPIO joystick inputs exposed as buttons, analog axes, or zero-wheel trigger.',
    fields: [
      {
        path: 'axis.gpiofilt',
        label: 'Analog filter',
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        defaultValue: 'false',
        description: 'Enables a global Biquad low-pass on GPIO analog axes before HID scaling.',
      },
      {
        path: 'axis.gpiofiltf',
        label: 'Filter cutoff',
        type: 'float',
        protocol: 'openffboard',
        min: 0.5,
        max: 500,
        step: 0.1,
        unit: 'Hz',
        defaultValue: '60',
        description: 'Cutoff frequency for the GPIO analog filter (0.5–500 Hz). Default 60 Hz.',
      },
      {
        path: 'axis.gpioautocal',
        label: 'Analog autocal',
        type: 'bool',
        protocol: 'openffboard',
        options: boolOptions,
        defaultValue: 'false',
        description: 'Tracks live min/max on analog GPIOs and updates gpio.N.amin/amax automatically.',
      },
      ...GPIO_CHANNELS.flatMap((gpio) => gpioChannelFields(gpio)),
    ],
  },
  {
    id: 'live',
    title: 'Live telemetry',
    description: 'Read-only runtime values for telemetry, dashboard, and debug. Not shown in config editors.',
    fields: [
      {
        path: 'axis.curpos',
        label: 'Wheel position',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'deg',
        description: 'Current wheel angle in degrees.',
      },
      {
        path: 'axis.curspd',
        label: 'Wheel speed',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'deg/s',
        description: 'Current wheel angular velocity.',
      },
      {
        path: 'axis.curtorque',
        label: 'FFB torque',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Raw FFB torque magnitude from OpenFFBoard (use diag T for Nm in charts).',
      },
      {
        path: 'axis.curaccel',
        label: 'Wheel acceleration',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'deg/s²',
        description: 'Current wheel angular acceleration in deg/s² (not deg/s).',
      },
      {
        path: 'main.ffbactive',
        label: 'FFB active flag',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: '1 when the firmware considers game FFB active (recent HID OUT traffic).',
      },
      {
        path: 'axis.zhits',
        label: 'Z index hits',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Accepted encoder Z-index pulses. Meaningful with incremental+Z; N/A on AS5047. SET 0 resets.',
      },
      {
        path: 'axis.zglitch',
        label: 'Z glitches',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Rejected Z IRQs (glitches). Meaningful with incremental+Z; N/A on AS5047. SET 0 resets.',
      },
      {
        path: 'odrv.vbus',
        label: 'VBUS (FFB ADC)',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'mV',
        description: 'Same VBUS ADC as r vbus_voltage, reported in millivolts. Divide by 1000 for volts. Not a second sensor.',
      },
    ],
  },
  {
    id: 'system',
    title: 'System',
    description: 'Board identity. VBUS divider is under PSU / Brake. Live telemetry is in Debug and Observe.',
    fields: [
      {
        path: 'sys.swver',
        label: 'OpenFFBoard compat version',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'OpenFFBoard compatibility string (hardcoded 1.17.0 on this firmware). Distinct from ODrive fw_version_* on Observe.',
      },
      {
        path: 'sys.hwtype',
        label: 'Hardware type',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'Hardware variant string (e.g. ODrive-Wheel).',
      },
      {
        path: 'sys.uid',
        label: 'STM32 UID',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: '96-bit STM32 unique ID (hex).',
      },
      {
        path: 'sys.devid',
        label: 'STM32 device ID',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'STM32 device ID and silicon revision.',
      },
      {
        path: 'sys.uptime',
        label: 'Uptime',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        unit: 'ms',
        description: 'Milliseconds since boot (HAL_GetTick).',
      },
      {
        path: 'sys.heap',
        label: 'Free heap (bytes)',
        type: 'readonly',
        protocol: 'openffboard',
        readonly: true,
        description: 'FreeRTOS heap remaining. A value below ~4 kB may cause instability.',
      },
    ],
  },
];

export const flatFields = configGroups.flatMap((group) => group.fields.map((field) => ({ ...field, groupId: group.id })));

export const fieldsByPath = new Map(flatFields.map((field) => [field.path, field]));

export function getFieldByPath(path: string): ConfigField | undefined {
  return fieldsByPath.get(path);
}
